### ISSUE TITLE
Add new template function for IfNullOrEmpty 

### ISSUE THREAD

**Issue by tklein** [straightdave/eps#18]
The Each function is very helpful, but I noticed that a regularly want to use a default value if the actual one isn't set.

This is mostly in loop where some parameter/options are global, but could be overwritten. Currently I use something like `<%= if ( $_.value ) { $_.value } else { $global.value ] %>`

Although this works perfectly it's quite some effort. A shorter version would be great.

BTW: Thanks for building and maintaining this templating engine, I really appreciate that :)

**Comment by straightdave** [comment]
It's our honor that you like it. Actually we should all thank to @dbroeglin who's the actual maintainer.
This time I will not allow myself to be lazy as before, leaving all to Dominique. I'll evaluate this new requirement myself. :smiley:

**Comment by dbroeglin** [comment]
Yes it makes perfect sense to add something like that. I was thinking about it for while already but I'm of two minds about how to name it. I would go with something like 

    OrElse $_.value $defaultValue

But is not really in line with usual PowerShell idioms which would be more like:

    Get-ValueOrDefault -Value $_.value -Default $defaultValue

What do you think ? In any case I will start implementing it soon and create a pull request.

**Comment by straightdave** [comment]
Thanks Dominique. I'm far way out of the world of Windows now. I should apologize and then eat my promise.

**Comment by dbroeglin** [comment]
#19 Created a first PR. In the end I went with `Get-OrElse` like Scala.
