### ISSUE TITLE
Confusing description regarding handling of <%%

### ISSUE THREAD

**Issue by fgather** [straightdave/eps#25]
Hi,

my goal is to do templating of a classic asp page using powershell. Those files usually contain <% and %> at different lines. However, EPS seems to need <%% and %%> being in the same block, at least this was the only constellation which did work for me. 

The description however is a little bit unclear on that topic. For me it indicates that <%% and %%> can be used completely apart from each other:
<%% and %%> : are replaced respectively by <% and %> in the output.

Can you give me a hint if I'm doing something stupid with EPS, if there is a bug in the implementation, or if the manual is wrong? 

Many Regards

**Comment by dbroeglin** [comment]
That is strange. There are several unit tests validating that a single `<%%` or `%%>` that seem to cover your use case. Can you give me more details about the templates you are trying to use ? Also, which version of EPS and PowerShell you are using ?

Here is an example of a template that seems to work properly in my environment (MacOSX, PS v6.0.1, EPS v0.5.0):

    PS > Invoke-EpsTemplate -Template @"                                                                                                                                  
    >> <%%                                                                                                                                                                          
    >> foo bar                                                                                                                                                                      
    >> %%>                                                                                                                                                                          
    >> "@
    <%
    foo bar
    %>

**Comment by dbroeglin** [comment]
@fgather I think I misunderstood your issue. After doing a bit more testing mixing tags I found the following error 👍 

```
PS > Invoke-EpsTemplate -Template "<%% <%= 1 %> %%>"
<% <%= 1 > %>
```
This should actually have returned `<% 1 %>`
I will work on solving this issue and post a fix in the coming days.

**Comment by dbroeglin** [comment]
@fgather I think I fixed all the issues related to `<%%` and `%%>`. But as you are actually using it in a real situation would it be possible for you to test this version of the code and confirm ?

**Comment by fgather** [comment]
Hi,

I'll try as soon as I can! Thanks for the effort!
