### ISSUE TITLE
Is it possible to make Invoke-EpsTemplate fail if a binding is missing?

### ISSUE THREAD

**Issue by fgimian** [straightdave/eps#30]
Hey there, wonderful job on this templating engine! 😄 

Currently, if a binding is missing, it seems to proceed silently.

e.g.

```
PS C:\Users\fots> type .\test.eps
Hello there <%= $Name %>, how are you today?
PS C:\Users\fots> Invoke-EpsTemplate -Path .\test.eps
Hello there , how are you today?

PS C:\Users\fots> $ErrorActionPreference = 'Stop'
PS C:\Users\fots> Invoke-EpsTemplate -Path .\test.eps
Hello there , how are you today?

PS C:\Users\fots> Invoke-EpsTemplate -Path .\test.eps -ErrorAction Stop
Hello there , how are you today?
```

Is there any way to make this more strict and fail if a variable is not set?

Thanks heaps
Fotis

**Comment by iCodeSometime** [comment]
I came here to request this same feature - or more specifically in my case, I'd like an option for Invoke-EpsTemplate to throw an error if the result of a `<%=` block comes out to null.

**Comment by iCodeSometime** [comment]
@fgimian see #31

**Comment by fgimian** [comment]
Thank you so much for implementing this @iCodeSometime and accepting it @straightdave!! 😄
