### ISSUE TITLE
ThrowForEmptyInsert not compatible with many features

### ISSUE THREAD

**Issue by plaisted** [straightdave/eps#34]
A simple scriptblock like this works in EPS:
```powershell
<%= if ($true) { "true" } else { "false" }  %>
```

However if the templating is invoked with ThrowForEmptyInsert, it throws the following error:
```
New-EpsTemplateScript : Exception calling "Create" with "1" argument(s): "At line:4 char:74
+ ... : `"");$sb.Append("$(if ($true) { "true" } else { "false" } | Get-OrE ...
+                                                                 ~
An empty pipe element is not allowed."
```

If the script block is wrapped like follows:
```powershell
<%= (if ($true) { "true" } else { "false" })  %>
```
the error no longer occurs but no output is created for the entire template (null).

I haven't had a chance to dig into this any further.

**Comment by plaisted** [comment]
I noticed I wrapped in parenthesis instead of a sub expression in the second example. Replacing the second with:
```powershell
<%= $(if ($true) { "true" } else { "false" })  %>
```
resulted in it working properly. It may be useful to automatically wrap code in a sub expression if the `ThrowForEmptyInsert` flag is on.

**Comment by straightdave** [comment]
@iCodeSometime Please take a look.

**Comment by iCodeSometime** [comment]
@straightdave see #33

**Comment by straightdave** [comment]
just merged one version, @plaisted would you please help check this again?

**Comment by plaisted** [comment]
I haven't extensively tested the new version but it fixes the specific issues I was having. Thanks, appreciate the fix @iCodeSometime
