### ISSUE TITLE
Uploading EPS to the PowerShell Gallery

### ISSUE THREAD

**Issue by dbroeglin** [straightdave/eps#7]
I'm using the last version of the code for some time now, it seems to work quite nicely. Also, I started using it in a module of my own: https://github.com/dbroeglin/Forge

I'm not copying it, I just do an `Import-Module EPS`, so it would be nice if someone wants to use it that they just can do an `Install-Module EPS` .

To facilitate the publication I added some information in the PSD1 file (see https://github.com/straightdave/eps/pull/6). You can just review and adapt it, create an account to access https://www.powershellgallery.com/packages/upload and do a `Publish-Module`.

I don't want to bother you more than necessary and if you do not have time I could do it for you. However, it would not be fair to your work as my account would be associated with the upload. And I think credit should be given where it is due! ;-)

**Comment by straightdave** [comment]
EPS is uploaded to the gallary:
https://www.powershellgallery.com/packages/EPS/0.2.0

if there is any issue about this uploading, please tell me, pal.

**Comment by dbroeglin** [comment]
Sorry for the delay, had some hectic few weeks. I just retested it with my own module and it seems to work just fine. Kudos and thank you!
